version: '3'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:? mongo user is needed}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:? mongo user is needed}
      - POSTGRES_DB=${POSTGRES_DB:? mongo user is needed}
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
